CREATE DATABASE VBPROJECT
GO
USE VBPROJECT
GO

CREATE TABLE TIEPNHAN
(
	BIENSO VARCHAR(50),
	HIEUXE VARCHAR(50),
	TENCHUXE VARCHAR(50),
	DIACHI VARCHAR(50),
	DIENTHOAI INT,
	NGAYTIEPNHAN VARCHAR(50)
    CONSTRAINT PK_TIEPNHAN PRIMARY KEY (BIENSO) 
)

CREATE TABLE SUACHUA
(
	SOLUONGPHUTUNG VARCHAR(50),
	VATTUPHUTUNG VARCHAR(50),
	BIENSO VARCHAR(50),
	TIENNO VARCHAR(50),
	TIENCONG VARCHAR(50),
)
CREATE TABLE THONGKE
(
    HIEUXE VARCHAR(50),
    THANG VARCHAR(50),
    TONGDOANHTHU VARCHAR(50),
	SOLUOTSUA VARCHAR(50),
	THANHTIEN VARCHAR(50),
	TILE VARCHAR(50),
	VATTUPHUTUNG VARCHAR(50),
	TONDAU VARCHAR(50),
	PHATSINH VARCHAR(50),
	TONCUOI VARCHAR(50),
	CONSTRAINT PK_THONGKE PRIMARY KEY (THANG)
)

ALTER TABLE THONGKE ADD FOREIGN KEY (HIEUXE) REFERENCES TIEPNHAN(HIEUXE)

--khong can gia tri thanh tien?--

--join 2 barng nay lai vs nhau--
--tam thoi co the chua can nhung t viet truoc co gi neu can thi uncomment ra dung--
--
SELECT TIEPNHAN.TENCHUXE,SUACHUA.TIENCONG
FROM TIEPNHAN
INNER JOIN SUACHUA
ON TIEPNHAN.BIENSO=SUACHUA.BIENSO
--
SELECT THONGKE.HIEUXE,TIEPNHAN.THANG
FROM THONGKE
INNER JOIN TIEPNHAN
ON THONGKE.HIEUXE=TIEPNHAN.HIEUXE

INSERT INTO TIEPNHAN VALUE ('','MAZDA','','','','');
INSERT INTO TIEPNHAN VALUE ('','TOYOTA','','','','');
INSERT INTO TIEPNHAN VALUE ('','HONDA','','','','');
INSERT INTO TIEPNHAN VALUE ('','LAMBORGHINI','','','','');
INSERT INTO TIEPNHAN VALUE ('','FERRARI','','','','');
INSERT INTO TIEPNHAN VALUE ('','FORD','','','','');
INSERT INTO TIEPNHAN VALUE ('','SUBARU','','','','');
INSERT INTO TIEPNHAN VALUE ('','KIA','','','','');
INSERT INTO TIEPNHAN VALUE ('','PORSCHE','','','','');
INSERT INTO TIEPNHAN VALUE ('','AUDI','','','','');
INSERT INTO SUACHUA VALUE (NHU TREN);
