CREATE DATABASE VBPROJECT
GO
USE VBPROJECT
GO

CREATE TABLE TIEPNHAN
(
	BIENSO VARCHAR(50),
	HIEUXE VARCHAR(50),
	TENCHUXE VARCHAR(50),
	DIACHI VARCHAR(50),
	DIENTHOAI INT,
	NGAYTIEPNHAN VARCHAR(50)
    CONSTRAINT PK_TIEPNHAN PRIMARY KEY (BIENSO) 
)

CREATE TABLE SUACHUA
(
	SOLUONGPHUTUNG VARCHAR(50),
	VATTUPHUTUNG VARCHAR(50),
	BIENSO VARCHAR(50),
	TIENNO VARCHAR(50),
	TIENCONG VARCHAR(50),
)

--khong can gia tri thanh tien?--

--join 2 barng nay lai vs nhau--
--tam thoi co the chua can nhung t viet truoc co gi neu can thi uncomment ra dung--
--
SELECT TIEPNHAN.TENCHUXE,SUACHUA.TIENCONG
FROM TIEPNHAN
INNER JOIN SUACHUA
ON TIEPNHAN.BIENSO=SUACHUA.BIENSO
--

INSERT INTO TIEPNHAN VALUE (KHI DU LIEU DC NHAP VO BANG THI NO SE TU DONG DC FILL O DAY);
INSERT INTO SUACHUA VALU (NHU TREN);
